name: RP2040 CI/CD

on:
  push:
    branches:
#       - main  # 或者您使用的其他主分支名称
        - pico_control_motor
  pull_request:
    branches:
#       - main  # 或者您使用的其他主分支名称
        - pico_control_motor

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cpplint

      - name: Code style check
        run: cpplint --recursive --extensions=c,h,cc,cpp,hpp --filter=-readability/casting,-runtime/int,-build/header_guard,-build/include_order ./

      - name: Build Docker image
        run: docker build -t rp2040-dev .

      - name: Build project
        run: |
          docker run --rm -v $(pwd):/rp2040/projects/my_project rp2040-dev /bin/bash -c "cd /rp2040/projects/my_project && mkdir build && cd build && cmake .. && make"
          mv build/my_project.uf2 my_project.uf2

      - name: Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          files: my_project.uf2
        env:
          GITHUB_TOKEN: ${{ secrets.CI }}
