name: Micro-ROS RP2040 Firmware Build

on:
  push:
    branches: [ "main" , "pico_control_motor" ]
  pull_request:
    branches: [ "main" , "pico_control_motor"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          git \
          cmake \
          gcc-arm-none-eabi \
          libnewlib-arm-none-eabi \
          build-essential \
          libstdc++-arm-none-eabi-newlib \
          python3 \
          python3-pip \
          python3-venv \
          python3-dev
          
    - name: setup env
      run: |
        git clone https://github.com/RaspberryPi/pico-sdk --recurse-submodules ~/pico-sdk
        git clone -b smp https://github.com/FreeRTOS/FreeRTOS-Kernel --recurse-submodules ~/FreeRTOS-Kernel
        git clone https://github.com/micro-ROS/micro_ros_raspberrypi_pico_sdk ~/micro_ROS_SDK_PATH
        git clone https://github.com/raspberrypi/pico-examples ~/pico-examples
        export PICO_SDK_PATH=~/pico-sdk
        export FREERTOS_KERNEL_PATH=~/FreeRTOS-Kernel
        export micro_ROS_SDK_PATH=~/micro_ROS_SDK_PATH
        export pico_examples_PATH=~/pico-examples
        
    - name: make
      run: |
        sudo apt update
        sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib -y
        git clone -b pico_control_motor https://github.com/tianrking/MicroROS_RP2040 ~/MicroROS_RP2040
        cd ~/MicroROS_RP2040
        export PICO_SDK_PATH=~/pico-sdk
        export FREERTOS_KERNEL_PATH=~/FreeRTOS-Kernel
        export micro_ROS_SDK_PATH=~/micro_ROS_SDK_PATH
        export pico_examples_PATH=~/pico-examples
        mkdir build 
        cd build 
        cmake ..
        make
        
    - name: Upload Firmware to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.CI_RELEASE_TOKEN }}
        file: ~/MicroROS_RP2040/build/pico_micro_ros_motor_control.uf2
        asset_name: pico_micro_ros_motor_control.uf2
        tag: ${{ github.ref }}
        overwrite: true
        prerelease: false    
    
      
    
